### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'slice' of undefined

### ISSUE THREAD

**Issue by achiko** [PolymathNetwork/polymath-contract-wrappers#190]
Getting Error:  Uncaught (in promise) TypeError: Cannot read property 'slice' of undefined

Code : 
```const HOST = "https://kovan.infura.io/v3/f116c5bde0874198ad8cf6c7d3606210"; // Infura 

const providerEngine = new Web3ProviderEngine();
providerEngine.addProvider(new RedundantSubprovider([new RPCSubprovider(HOST)]));
providerEngine.start();

const params = {
    provider: new Web3.providers.HttpProvider(HOST) ,
    polymathRegistryAddress: "0x5b215a7d39ee305ad28da29bf2f0425c6c2a00b3"
};
  // Instantiate the API
const polymathAPI = new PolymathAPI(params);

const ticker = 'MARKETLND';
const tokenAddress = await polymathAPI.securityTokenRegistry.getSecurityTokenAddress(ticker);
const TEST = await polymathAPI.tokenFactory.getSecurityTokenInstanceFromAddress(tokenAddress);
```
**polymathRegistryAddress: "0x5b215a7d39ee305ad28da29bf2f0425c6c2a00b3"  is taken from** 
[https://kovan.etherscan.io/address/0xb127905265530fc61f3C3A0FD0eFF7A41d50D921#readContract
](https://kovan.etherscan.io/address/0xb127905265530fc61f3C3A0FD0eFF7A41d50D921#readContract
)

![image](https://user-images.githubusercontent.com/3051858/63425713-42ca5800-c422-11e9-9202-64da8711e9dd.png)

**Comment by VictorVicente** [comment]
Hey @achiko, thanks for your feedback!
The problem here is that you're trying to create the instance with a web3 provider and you should use the providerEngine you started above instead.
You could check different providers configurations on our readme.md where you can find some examples.

Tell us if you have any trouble.
